# Generated by Django 4.2.2 on 2023-06-28 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_booking_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='booking_time',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='occasion',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
